services:
  tor:
    image: dperson/torproxy
    container_name: tor-proxy
    restart: unless-stopped
    networks:
      - osint-network
    ports:
      - "9050:9050"
      - "8118:8118"
    command: ["-n"]
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9050 || exit 1"]
      interval: 30s
      retries: 10
      start_period: 20s

  kali-osint:
    build:
      context: ./kali-osint
      dockerfile: Dockerfile
    container_name: kali-osint
    privileged: true
    restart: unless-stopped
    depends_on:
      tor:
        condition: service_healthy
    networks:
      - osint-network
    environment:
      - http_proxy=http://tor-proxy:8118
      - https_proxy=http://tor-proxy:8118
      - ALL_PROXY=socks5://tor-proxy:9050
    volumes:
      - ./data:/osint_results
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  osint-network:
    driver: bridge
